### PR TITLE
Add dotnet 8 sdk support

### PR DESCRIPTION
**Pull request by nathangmahler1987**

### CODE REVIEW

**Comment by cleftheris** [comment]
Keep it simple just update global.json and appveyor.yml to sdk "8.0.300" so that I can accept. Leave the target frameworks out for the moment.

**Comment by nathangmahler1987** [comment]
Sorry for the delay, thank you for the feedback, this aspect of programming (sdk's, frameworks, etc.) is relatively new to me

**Review by nathangmahler1987 — COMMENTED** [review]
Sorry it took so long! 3 kids below 4 can keep you busy:)

**Comment by nathangmahler1987** [comment]
@cleftheris Why does the PR always fail the check with AppVeyor (don't have any experience with this product). What is the issue since the changes in this PR are small since it is only changing the global.json file and apveyor.yml file. Thank you again for your patience with me!

**Comment by cleftheris** [comment]
Hi @nathangmahler1987,

Its kind of tricky. The main reason is that AppVeyor base image for build/test is VS2019 (not the VS2022) and this is on purpose because it has [preinstalled the Dotnet Framework 4.5.1 target](https://learn.microsoft.com/en-us/dotnet/framework/install/guide-for-developers) but does not have the dotnet 6 onwards SDKs. 

Now the build with the changes you made breaks when trying to discover and run tests the library builds fine. When this happens it searches for the test SDK for dotnet 6.0 to run the tests and it cannot find it (which makes sense since we changed to SDK 8.0). 

There are tree options 

1. Install the dotnet6.0 SDK side by side with dotnet 8
2. Change the base image to VS2022 but have to Install the FullFramework 4.5 sdk on prepare stage.
3. Change the test project to target the newest SDK.

The easiest option here is to change the target framework for the tests project to `<TargetFramework>net80</TargetFramework>`

**Comment by amduncan777** [comment]
@cleftheris What's the reason for needing to target .NET Framework 4.5.1?

**Comment by cleftheris** [comment]
Good question :D

The main reason is that when the project started (2015) the most interest for the library came from FullFramework developers. 
I have plans to remove the multiple target frameworks and keep maybe only the netstandard2.1 as well as a couple of LTS dotnet releases.

**Comment by amduncan777** [comment]
Ok that's what I figured. Makes sense.

**Comment by nathangmahler1987** [comment]
@cleftheris like two weeks ago I made those you suggested, can you see them in the PR? Or do I need to do another PR I thought once I did them and pushed them the PR would reflect it and the files changed looks correct does it work differently when I essentially just pushed it to my fork? I have been out camping for a bit but will get home this weekend so I could do more in depth work on it soon:)

**Comment by cleftheris** [comment]
I have made additional changes in the master branch so I will merge now that the codebase is working.

**Pull request merged**
